# Generated by Django 5.0.1 on 2024-04-19 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('phone_number', models.CharField(max_length=255)),
                ('street_address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('user_type', models.CharField(choices=[('Patient', 'Patient'), ('Specialist', 'Specialist')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='profiles.user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='profiles.user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Doctor', 'Doctor'), ('Dentist', 'Dentist'), ('Pharmacist', 'Pharmacist'), ('Nurse', 'Nurse'), ('Therapist', 'Therapist'), ('Psychologist', 'Psychologist'), ('Dietitian', 'Dietitian'), ('Physiotherapist', 'Physiotherapist'), ('Optometrist', 'Optometrist'), ('Chiropractor', 'Chiropractor'), ('Occupational Therapist', 'Occupational Therapist'), ('Speech Therapist', 'Speech Therapist'), ('Radiologist', 'Radiologist'), ('Surgeon', 'Surgeon'), ('Cardiologist', 'Cardiologist'), ('Dermatologist', 'Dermatologist'), ('Endocrinologist', 'Endocrinologist'), ('Gastroenterologist', 'Gastroenterologist'), ('Hematologist', 'Hematologist'), ('Neurologist', 'Neurologist'), ('Oncologist', 'Oncologist'), ('Pediatrician', 'Pediatrician'), ('Psychiatrist', 'Psychiatrist'), ('Rheumatologist', 'Rheumatologist'), ('Urologist', 'Urologist'), ('Allergist', 'Allergist'), ('Anesthesiologist', 'Anesthesiologist'), ('Cardiothoracic Surgeon', 'Cardiothoracic Surgeon'), ('Critical Care Specialist', 'Critical Care Specialist'), ('Emergency Medicine Specialist', 'Emergency Medicine Specialist'), ('Family Physician', 'Family Physician'), ('Geriatrician', 'Geriatrician'), ('Infectious Disease Specialist', 'Infectious Disease Specialist'), ('Internist', 'Internist'), ('Medical Geneticist', 'Medical Geneticist'), ('Nephrologist', 'Nephrologist'), ('Pulmonologist', 'Pulmonologist'), ('Radiation Oncologist', 'Radiation Oncologist'), ('Sleep Medicine Specialist', 'Sleep Medicine Specialist'), ('Sports Medicine Specialist', 'Sports Medicine Specialist'), ('Vascular Surgeon', 'Vascular Surgeon'), ('Acupuncturist', 'Acupuncturist'), ('Audiologist', 'Audiologist'), ('Ayurvedic Doctor', 'Ayurvedic Doctor'), ('Chiropractor', 'Chiropractor'), ('Homeopath', 'Homeopath')], max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.specialist')),
            ],
        ),
    ]
