# Generated by Django 5.0.1 on 2024-03-29 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_specialist_specialization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.specialization'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
