# Generated by Django 5.0.1 on 2024-04-17 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medics', '0001_initial'),
        ('profiles', '0002_alter_specialization_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptom',
            name='patient',
            field=models.ForeignKey(default='3', on_delete=django.db.models.deletion.CASCADE, to='profiles.user'),
        ),
    ]
