# Generated by Django 5.0.1 on 2024-04-18 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medics', '0002_symptom_patient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Symptom',
        ),
    ]
