# Generated by Django 5.0.1 on 2024-04-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='meeting_room_id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='symptom',
        ),
        migrations.AddField(
            model_name='appointment',
            name='symptom_description',
            field=models.TextField(default='How Exactly do you feel'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='symptom_type',
            field=models.CharField(default='General', max_length=255),
        ),
    ]
